routes/web.php
<?php

use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::get('', 'HomeController@index')->name('index');
Route::get('/en', 'HomeController@index')->name('index');
Route::post('contact', 'HomeController@send')->name('contact');
Route::post('locations/json', 'LocationController@json')->name('locations.json');
Route::post('locations/location/coordinates', 'LocationController@locationCoordinates')->name('locations.coordinates');
Route::post('categories/json', 'CategoryController@json')->name('categories.json');
Route::post('languages/json', 'LanguageController@json')->name('languages.json');
Route::post('months/json', 'MonthController@json')->name('months.json');
Route::post('admin/reset/password', 'PasswordresetController@init')->name('reset.init');
Route::post('admin/reset/password/finish', 'PasswordresetController@reset')->name('reset.reset');
Route::get('admin/reset/password/token/{token}', 'PasswordresetController@showResetForm')->name('reset.form');
Route::get('api/test', 'ApiTest\ApiTestController@index')->name('api.index');
Route::get('api/test/{id}', 'ApiTest\ApiTestController@sample')->name('api.sample');

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {
    Route::get('map', 'HomeController@map')->name('map');
    Route::get('contact', 'HomeController@contact')->name('contact');
    Route::get('js/lang.js', 'LangController@init')->name('assets.lang');

    Route::group(['middleware' => 'published'], function () {
        Route::get('location/{id}', 'LocationController@get')->name('location.get');
    });
});

Route::group(['as' => 'admin.', 'namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::get('', 'AdminController@index')->name('index');
    Route::post('login', 'AdminController@login')->name('login');
    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('profile', 'AdminController@updateProfile')->name('profile');
    Route::post('password', 'AdminController@changePassword')->name('password');
    Route::get('categories', 'CategoryController@index')->name('categories.index');
    Route::post('categories', 'CategoryController@create')->name('categories.create');
    Route::post('categories/json', 'CategoryController@json')->name('categories.json');
    Route::get('languages', 'LanguageController@index')->name('languages.index');
    Route::post('languages', 'LanguageController@create')->name('languages.create');
    Route::post('languages/json', 'LanguageController@json')->name('languages.json');
    Route::get('images/junk', 'ImageController@deleteJunk')->name('images.junk.delete');
    Route::get('locations', 'LocationController@index')->name('locations.index');
    Route::get('locations/create', 'LocationController@createForm')->name('locations.create.form');
    Route::get('locations/edit/{id}', 'LocationController@editForm')->name('locations.edit.form');
    Route::post('locations/edit/{id}', 'LocationController@update')->name('locations.update');
    Route::get('locations/delete/{id}', 'LocationController@delete')->name('locations.delete');
    Route::post('location/image/thumbnail', 'LocationController@changeThumbnail')->name('location.thumbnail');
    Route::post('location/image/thumbnail/crop', 'LocationController@cropThumbnail')->name('location.thumbnail.crop');
    Route::post('locations', 'LocationController@create')->name('locations.create');
    Route::post('images/upload', 'LocationController@upload')->name('locations.upload');
    Route::post('locations/json', 'LocationController@json')->name('locations.json');
    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::post('contact', 'ContactController@update')->name('contact.update');
    Route::get('contact/destroy', 'ContactController@destroy')->name('contact.destroy');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::post('settings', 'SettingsController@update')->name('settings.update');
    Route::get('logout', 'AdminController@logout')->name('logout');
});

resources/views/admin/parts/header.blade.php
<header class="m-grid__item    m-header "  data-minimize-mobile="hide" data-minimize-offset="200" data-minimize-mobile-offset="200" data-minimize="minimize" style="background-color: #f2f3f8;">
    <div class="m-container m-container--fluid m-container--full-height">
        <div class="m-stack m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-brand  m-brand--skin-dark ">
                <div class="m-stack m-stack--ver m-stack--general">
                    <div class="m-stack__item m-stack__item--middle m-brand__logo">
                        <a href="{{ route('admin.index') }}" class="m-brand__logo-wrapper">
                            @php
                                $settings = App\Settings::first();
                            @endphp
                            <img alt="" src="{{ secure_asset('uploads/' . optional($settings)->logo_url) }}" width="60px" />
{{--                            <img alt="" src="{{ secure_asset('assets/img/logo-footer.png') }}" width="60px" />--}}
                        </a>
                    </div>
                    <div class="m-stack__item m-stack__item--middle m-brand__tools">
                        <a href="javascript:;" id="m_aside_left_minimize_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-desktop-inline-block">
                            <span></span>
                        </a>
                        <a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
                            <span></span>
                        </a>
                        <a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
                            <span></span>
                        </a>
                        <a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
                            <i class="flaticon-more"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav"></div>
        </div>
    </div>
</header>

resources/views/admin/parts/sidebar.blade.php
<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " data-menu-vertical="true" data-menu-scrollable="false" data-menu-dropdown-timeout="500">
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Dashboard
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.profile') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Update Profile
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.logout') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Logout
                            </span>
                        </span>
                    </span>
                </a>
            </li>
            <li class="m-menu__section">
                <h4 class="m-menu__section-text">
                    Pages
                </h4>
                <i class="m-menu__section-icon flaticon-more-v3"></i>
            </li>
            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.categories.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Categories
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.languages.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Languages
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.locations.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Locations
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.contact.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Contact
                            </span>
                        </span>
                    </span>
                </a>
            </li>

            <li class="m-menu__item " aria-haspopup="true" >
                <a  href="{{ route('admin.settings.index') }}" class="m-menu__link ">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-title">
                        <span class="m-menu__link-wrap">
                            <span class="m-menu__link-text">
                                Settings
                            </span>
                        </span>
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>