routes/web.php
<?php

use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::get('', 'HomeController@index')->name('index');
Route::get('/en', 'HomeController@index')->name('index');
Route::post('contact', 'HomeController@send')->name('contact');
Route::post('locations/json', 'LocationController@json')->name('locations.json');
Route::post('locations/location/coordinates', 'LocationController@locationCoordinates')->name('locations.coordinates');
Route::post('categories/json', 'CategoryController@json')->name('categories.json');
Route::post('languages/json', 'LanguageController@json')->name('languages.json');
Route::post('months/json', 'MonthController@json')->name('months.json');
Route::post('admin/reset/password', 'PasswordresetController@init')->name('reset.init');
Route::post('admin/reset/password/finish', 'PasswordresetController@reset')->name('reset.reset');
Route::get('admin/reset/password/token/{token}', 'PasswordresetController@showResetForm')->name('reset.form');
Route::get('api/test', 'ApiTest\ApiTestController@index')->name('api.index');
Route::get('api/test/{id}', 'ApiTest\ApiTestController@sample')->name('api.sample');

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {
    Route::get('map', 'HomeController@map')->name('map');
    Route::get('contact', 'HomeController@contact')->name('contact');
    Route::get('js/lang.js', 'LangController@init')->name('assets.lang');

    Route::group(['middleware' => 'published'], function () {
        Route::get('location/{id}', 'LocationController@get')->name('location.get');
    });
});

Route::group(['as' => 'admin.', 'namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::get('', 'AdminController@index')->name('index');
    Route::post('login', 'AdminController@login')->name('login');
    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('profile', 'AdminController@updateProfile')->name('profile');
    Route::post('password', 'AdminController@changePassword')->name('password');
    Route::get('categories', 'CategoryController@index')->name('categories.index');
    Route::post('categories', 'CategoryController@create')->name('categories.create');
    Route::post('categories/json', 'CategoryController@json')->name('categories.json');
    Route::get('languages', 'LanguageController@index')->name('languages.index');
    Route::post('languages', 'LanguageController@create')->name('languages.create');
    Route::post('languages/json', 'LanguageController@json')->name('languages.json');
    Route::get('images/junk', 'ImageController@deleteJunk')->name('images.junk.delete');
    Route::get('locations', 'LocationController@index')->name('locations.index');
    Route::get('locations/create', 'LocationController@createForm')->name('locations.create.form');
    Route::get('locations/edit/{id}', 'LocationController@editForm')->name('locations.edit.form');
    Route::post('locations/edit/{id}', 'LocationController@update')->name('locations.update');
    Route::get('locations/delete/{id}', 'LocationController@delete')->name('locations.delete');
    Route::post('location/image/thumbnail', 'LocationController@changeThumbnail')->name('location.thumbnail');
    Route::post('location/image/thumbnail/crop', 'LocationController@cropThumbnail')->name('location.thumbnail.crop');
    Route::post('locations', 'LocationController@create')->name('locations.create');
    Route::post('images/upload', 'LocationController@upload')->name('locations.upload');
    Route::post('locations/json', 'LocationController@json')->name('locations.json');
    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::post('contact', 'ContactController@update')->name('contact.update');
    Route::get('contact/destroy', 'ContactController@destroy')->name('contact.destroy');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::post('settings', 'SettingsController@update')->name('settings.update');
    Route::get('logout', 'AdminController@logout')->name('logout');
});

resources/views/admin/pages/categories.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="block-header">
        <h2>Categories</h2>
    </div>

    <div class="card">
        <div class="row">
            <div class="col-sm-4">
                <form action="{{ route('admin.categories.create') }}" method="POST" class="form-horizontal" role="form">
                    <div class="card-body card-padding" style="border-right: 1px solid rgba(44, 47, 63, 0.14); border-bottom: 1px solid rgba(44, 47, 63, 0.14);">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="name_ka" class="form-control m-input" id="name_ka" placeholder="Category Name - KA *" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="name_en" class="form-control m-input" id="name_en" placeholder="Category Name - EN" required>
                            </div>
                        </div>

                        {{ csrf_field() }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-sm-8" id="table-categories"></div>
        </div>
    </div>
@endsection

@section('EOB')
    <script>
        $(document).ready(function () {
            window.currentDataTablesURL = '{!! route('admin.categories.json') !!}';

            $('#table-categories').mDatatable({
                data: {
                    type: 'remote',
                    source:  {
                        read: {
                            url: window.currentDataTablesURL
                        }
                    },
                    pageSize: 10,
                    saveState: {
                        cookie: true,
                        webstorage: true
                    },
                    serverPaging: false,
                    serverFiltering: false,
                    serverSorting: false
                },
                layout: {
                    theme: 'default',
                    class: 'm-datatable--brand',
                    scroll: false,
                    height: null,
                    footer: false,
                    header: true,
                    smoothScroll: {
                        scrollbarShown: true
                    },
                    spinner: {
                        overlayColor: '#000000',
                        opacity: 0,
                        type: 'loader',
                        state: 'brand',
                        message: true
                    },
                    icons: {
                        sort: {asc: 'la la-arrow-up', desc: 'la la-arrow-down'},
                        pagination: {
                            next: 'la la-angle-right',
                            prev: 'la la-angle-left',
                            first: 'la la-angle-double-left',
                            last: 'la la-angle-double-right',
                            more: 'la la-ellipsis-h'
                        },
                        rowDetail: {expand: 'fa fa-caret-down', collapse: 'fa fa-caret-right'}
                    }
                },
                sortable: false,
                pagination: true,
                columns: [{
                    field: "id",
                    title: "#",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 40,
                    selector: {class: 'm-checkbox--solid m-checkbox--brand'}
                }, {
                    field: "name",
                    title: "Name",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 150
                }],
                toolbar: {
                    layout: ['pagination', 'info'],
                    placement: ['bottom'],
                    items: {
                        pagination: {
                            type: 'default',
                            pages: {
                                desktop: {
                                    layout: 'default',
                                    pagesNumber: 6
                                },
                                tablet: {
                                    layout: 'default',
                                    pagesNumber: 3
                                },
                                mobile: {
                                    layout: 'compact'
                                }
                            },
                            navigation: {
                                prev: true,
                                next: true,
                                first: true,
                                last: true
                            },
                            pageSizeSelect: [10, 20, 30, 50, 100]
                        },
                        info: true
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/pages/contact.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="block-header">
        <h2>Contact</h2>
    </div>

    <div class="card">
        <div class="row">
            <div class="col-sm-4">
                <form action="{{ route('admin.contact.update') }}" method="POST" class="form-horizontal" role="form">
                    <div class="card-body card-padding">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="address" class="form-control m-input" id="contact_address" placeholder="Address *" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="email" name="email" class="form-control m-input" id="contact_email" placeholder="Email *" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="mnumber" class="form-control m-input" id="contact_mnumber" placeholder="Mobile Number *" required>
                            </div>
                        </div>

                        {{ csrf_field() }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-sm-8">
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon">
                                    <i class="flaticon-placeholder-2"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Contact Information
                                </h3>
                            </div>
                        </div>
                        <div class="m-portlet__head-tools">
                            <ul class="m-portlet__nav">
                                <li class="m-portlet__nav-item">
                                    <a href="{{ route('admin.contact.destroy') }}" class="m-portlet__nav-link m-portlet__nav-link--icon">
                                        <i class="la la-close"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="m-portlet__body">
                        <p>
                            Address: {{ $contact->address }}
                        </p>

                        <p>
                            Email: {{ $contact->email }}
                        </p>

                        <p>
                            Mobile Number: {{ $contact->mnumber }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/dashboard.blade.php
@extends('admin.layouts.app')

{{--@section('content')--}}
    {{--<div class="block-header">--}}
        {{--<h2>Dashboard</h2>--}}
    {{--</div>--}}
{{--@endsection--}}

resources/views/admin/pages/languages.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="block-header">
        <h2>Languages</h2>
    </div>

    <div class="card">
        <div class="row">
            <div class="col-sm-4">
                <form action="{{ route('admin.languages.create') }}" method="POST" class="form-horizontal" role="form">
                    <div class="card-body card-padding" style="border-right: 1px solid rgba(44, 47, 63, 0.14); border-bottom: 1px solid rgba(44, 47, 63, 0.14);">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="code" class="form-control m-input" id="lang_code" placeholder="Language Code *" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="ka[name]" class="form-control m-input" id="lang_name" placeholder="Language Name - KA" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="en[name]" class="form-control m-input" id="lang_name" placeholder="Language Name - EN">
                            </div>
                        </div>

                        {{ csrf_field() }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-sm-8" id="table-categories"></div>
        </div>
    </div>
@endsection

@section('EOB')
    <script>
        $(document).ready(function () {
            window.currentDataTablesURL = '{!! route('admin.languages.json') !!}';

            $('#table-categories').mDatatable({
                data: {
                    type: 'remote',
                    source:  {
                        read: {
                            url: window.currentDataTablesURL
                        }
                    },
                    pageSize: 10,
                    saveState: {
                        cookie: true,
                        webstorage: true
                    },
                    serverPaging: false,
                    serverFiltering: false,
                    serverSorting: false
                },
                layout: {
                    theme: 'default',
                    class: 'm-datatable--brand',
                    scroll: false,
                    height: null,
                    footer: false,
                    header: true,
                    smoothScroll: {
                        scrollbarShown: true
                    },
                    spinner: {
                        overlayColor: '#000000',
                        opacity: 0,
                        type: 'loader',
                        state: 'brand',
                        message: true
                    },
                    icons: {
                        sort: {asc: 'la la-arrow-up', desc: 'la la-arrow-down'},
                        pagination: {
                            next: 'la la-angle-right',
                            prev: 'la la-angle-left',
                            first: 'la la-angle-double-left',
                            last: 'la la-angle-double-right',
                            more: 'la la-ellipsis-h'
                        },
                        rowDetail: {expand: 'fa fa-caret-down', collapse: 'fa fa-caret-right'}
                    }
                },
                sortable: false,
                pagination: true,
                columns: [{
                    field: "id",
                    title: "#",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 40,
                    selector: {class: 'm-checkbox--solid m-checkbox--brand'}
                }, {
                    field: "name",
                    title: "Name",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 150
                }],
                toolbar: {
                    layout: ['pagination', 'info'],
                    placement: ['bottom'],
                    items: {
                        pagination: {
                            type: 'default',
                            pages: {
                                desktop: {
                                    layout: 'default',
                                    pagesNumber: 6
                                },
                                tablet: {
                                    layout: 'default',
                                    pagesNumber: 3
                                },
                                mobile: {
                                    layout: 'compact'
                                }
                            },
                            navigation: {
                                prev: true,
                                next: true,
                                first: true,
                                last: true
                            },
                            pageSizeSelect: [10, 20, 30, 50, 100]
                        },
                        info: true
                    }
                }
            });
        });
    </script>
@endsection

resources/views/admin/pages/locations.blade.php
@extends('admin.layouts.app')

@section('EOH')
    <link rel="stylesheet" href="{{ secure_asset('admin-assets/vendors/custom/Trumbowyg/dist/ui/trumbowyg.css') }}" />
@endsection

@section('content')
    <div class="block-header" style="display: flex; justify-content: space-between; margin-bottom: 3rem;">
        <h2>Locations</h2>
        <div style="display: flex;">
            <input type="text" name="locations_search" id="locations_search" class="form-control m-input" placeholder="Search Location" style="margin-right: 20px;" />

            <a class="btn btn-primary" href="{{ route('admin.locations.create.form') }}" style="margin-right: 20px;">Create new</a>
            <a class="btn btn-danger" href="{{ route('admin.images.junk.delete') }}">Clean junk images - {{ junkCount() }} image(s)</a>
        </div>
    </div>

    <div class="card">
        <div class="row">
            <div class="col-sm-12" id="table-locations"></div>
        </div>
    </div>

    <!--begin::Modal-->
    <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">
                        Delete Location
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">
                            &times;
                        </span>
                    </button>
                </div>
                <div class="modal-body" id="images-modal-body">
                    <span>Are you sure you want to delete location ?</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Cancel
                    </button>
                    <button type="button" class="btn btn-danger" id="delete-location">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
@endsection

@section('EOB')
    <script>
        $(document).ready(function () {
            window.currentDataTablesURL = '{!! route('admin.locations.json') !!}';

            let locations_datatable = $('#table-locations').mDatatable({
                data: {
                    type: 'remote',
                    source:  {
                        read: {
                            url: window.currentDataTablesURL
                        }
                    },
                    pageSize: 10,
                    saveState: {
                        cookie: true,
                        webstorage: true
                    },
                    serverPaging: false,
                    serverFiltering: false,
                    serverSorting: false,
                },
                layout: {
                    theme: 'default',
                    class: 'm-datatable--brand',
                    scroll: false,
                    height: null,
                    footer: false,
                    header: true,
                    smoothScroll: {
                        scrollbarShown: true
                    },
                    spinner: {
                        overlayColor: '#000000',
                        opacity: 0,
                        type: 'loader',
                        state: 'brand',
                        message: true
                    },
                    icons: {
                        sort: {asc: 'la la-arrow-up', desc: 'la la-arrow-down'},
                        pagination: {
                            next: 'la la-angle-right',
                            prev: 'la la-angle-left',
                            first: 'la la-angle-double-left',
                            last: 'la la-angle-double-right',
                            more: 'la la-ellipsis-h'
                        },
                        rowDetail: {expand: 'fa fa-caret-down', collapse: 'fa fa-caret-right'}
                    }
                },
                sortable: false,
                pagination: true,
                search: {
                    input: $('#locations_search')
                },
                columns: [{
                    field: "id",
                    title: "#",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 40,
                    selector: {class: 'm-checkbox--solid m-checkbox--brand'}
                }, {
                    field: "name",
                    title: "Name",
                    locked: {left: 'xl'},
                    sortable: false,
//                    width: 150
                },{
                    field: "category",
                    title: "Category",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 80,
                    template: function (row) {
                        var id = row.category.name;

                        return id;
                    }
                }, {
                    field: "edit",
                    title: "Edit",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 50,
                    template: function (row) {
                        var id = row.id;

                        return '\
                            <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill btn-location-edit" title="Edit Location" id="' + id + '">\
                                <i class="la la-edit"></i>\
                            </a>\
					    ';
                    }
                }, {
                    field: "delete",
                    title: "Delete",
                    locked: {left: 'xl'},
                    sortable: false,
                    width: 50,
                    template: function (row) {
                        var id = row.id;

                        return '\
                            <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill btn-location-delete" title="Delete Location" id="' + id + '">\
                                <i class="la la-trash"></i>\
                            </a>\
					    ';
                    }
                }],
                toolbar: {
                    layout: ['pagination', 'info'],
                    placement: ['bottom'],
                    items: {
                        pagination: {
                            type: 'default',
                            pages: {
                                desktop: {
                                    layout: 'default',
                                    pagesNumber: 6
                                },
                                tablet: {
                                    layout: 'default',
                                    pagesNumber: 3
                                },
                                mobile: {
                                    layout: 'compact'
                                }
                            },
                            navigation: {
                                prev: true,
                                next: true,
                                first: true,
                                last: true
                            },
                            pageSizeSelect: [10, 20, 30, 50, 100]
                        },
                        info: true
                    }
                }
            });

            $('#locations_search').on('change', function () {
                locations_datatable.search($(this).val());
            });
        });

        $(document).on('click', '.btn-location-edit', function (event) {
            event.preventDefault();

            let elementID = $(this).attr('id');

            location.href = '/admin/locations/edit/' + elementID;
        });

        $(document).on('click', '.btn-location-delete', function (event) {
            event.preventDefault();

            let elementID = $(this).attr('id');

            $('#delete_modal').modal();
            
            $('#delete-location').click(function () {
                location.href = '/admin/locations/delete/' + elementID;

                $('#delete_modal').modal('hide');
            });
        });
    </script>
@endsection

resources/views/admin/pages/settings.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="block-header">
        <h2>Settings</h2>
    </div>

    <div class="card">
        <div class="row">
            <div class="col-sm-8">
                <form action="{{ route('admin.settings.update') }}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                    <div class="card-body card-padding">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <label for="logo">Change website logo</label>
                                <input type="file" name="logo" id="logo" class="form-control m-input" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                <input type="text" name="name" class="form-control m-input" placeholder="Website name" value="{{ $settings->site_name }}" />
                            </div>
                        </div>

                        {{ csrf_field() }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-sm-4" id="table-categories">
                <div class="settings-logo-container" style="background: url({{ secure_asset('uploads/' . $settings->logo_url) }}) no-repeat; -webkit-background-size: contain;background-size: contain; width: 50%; height: 100%;"></div>
            </div>
        </div>
    </div>
@endsection